### ISSUE TITLE
Python 3 to Python 2

### ISSUE THREAD

**Issue by kadarakos** [kadarakos/python-course#1]
Should we change the syntax in the notebooks from Python 3 to Python 2 where necessary or should we teach Python 3?

**Comment by ghost-hacked** [comment]
What would be the reason for reverting back to Python 2 in certain sections?

**Comment by kadarakos** [comment]
I think all people in the department use Python 2 and it would make working with the students in the thesis etc. more effortless. Is it a bad plan?

**Comment by ghost-hacked** [comment]
If using Python 2 would be generally more beneficial to you and the people you're working with, then I don't think it would necessarily be a bad plan. However, more and more people are using Python 3, and it might not be a bad idea to have people switch over now and not later. If you look around, tutorials, projects on GitHub, books, etc. are all starting to use Python 3, so I would personally say to just go ahead and use Python 3, but it all really depends on what you're needing.

**Comment by kadarakos** [comment]
On my part I'm convinced.k
