### ISSUE TITLE
Judgement Day

### ISSUE THREAD

**Issue by kadarakos** [kadarakos/python-course#7]
Hey,

When does the course need to be finished for the first run? 
If it is for September let's decide on the last few modifications!
1. I suggest to put the un-used chapters in an old-chapters folder and keep the rest in the root
2. Have the final/live course on master and create a dev-branch when the course starts, where we add all the modifications that come up during the course and leave the master untouched

**Comment by swubb** [comment]
Hey,

I’ll be back monday and then I plan to power edit the remaining chapters, the course starts 31st of august. If we have the first half of the course ready by then that would be cool.

Best,
Sander

On 19 Aug 2015, at 22:53, kadarakos <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey,

When does the course need to be finished for the first run?
If it is for September let's decide on the last few modifications!
1.  I suggest to put the un-used chapters in an old-chapters folder and keep the rest in the root
2.  Have the final/live course on master and create a dev-branch when the course starts, where we add all the modifications that come up during the course and leave the master untouched

**Comment by kadarakos** [comment]
Actually I think we should do it the way the LxMLS guys did it. Have whatever on the master that we need for the developement and have a student branch that has a version that can be cloned for the students.

**Comment by kadarakos** [comment]
Minor suggestion for "Dictionaries.ipynb". The chapter does not go through important dictionary operators and methods
- key in dict
- len(dict)
- .update()
- .get()
-  .items / iteritems / .keys / .values

**Comment by pspronck** [comment]
I'd like to talk to you guys on Monday or Tuesday on how to integrate the
stuff in the master course, and then I can also start making upgrades
(extra exercises and such).

On Sun, Aug 23, 2015 at 1:16 PM, kadarakos notifications@github.com wrote:

> Minor suggestion for "Dictionaries.ipynb". The chapter does not go through
> important dictionary operators and methods
> - key in dict
> - len(dict)
> - .update()
> - .get()
> - .items / iteritems / .keys / .values
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kadarakos/python-course/issues/7#issuecomment-133818103
> .

## 

---

Pieter Spronck
p.spronck@gmail.com
http://www.spronck.net

**Comment by kadarakos** [comment]
I'll fly back on the 29th, but we can definitely arrange hangouts or skype,
